### ISSUE TITLE
firewall.tf - https://ipv6.icanhazip.com isnt working 

### ISSUE THREAD

**Issue by defyjoy** [hcloud-talos/terraform-hcloud-talos#10]
The module doesn't work as https://ipv6.icanhazip.com isnt working . This needs to be parameterized else the module is totally unsable if https://ipv6.icanhazip.com is down

**Comment by mpepping** [comment]
'No route to host' message? You probably don't have IPv6 then. Work around it by only setting [your IPv4 address](https://ipv4.icanhazip.com/) via the static lists in TF variables:

```
  firewall_kube_api_source  = ["169.254.169.254/32"]
  firewall_talos_api_source = ["169.254.169.254/32"]
  firewall_use_current_ip   = false
```

**Comment by mrclrchtr** [comment]
As @mpepping says, it can already be parameterized. Thanks for the hint.

Is there anything else missing @defyjoy ?
