### ISSUE TITLE
Cilium pod error on fresh install

### ISSUE THREAD

**Issue by saashqdev** [hcloud-talos/terraform-hcloud-talos#150]
Hi:
I'm running K8s 1.31.4 / Cilium 1.16.5 / Talos v1.9.0 and did a successful terraform install. I have one cilium pod that gets the following error:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox "701dcc0446969772b19b87674d6dec658a5c5b4c115fc33873f27d96be1c682e": failed to get sandbox image "registry.k8s.io/pause:3.10": failed to pull image "registry.k8s.io/pause:3.10": failed to pull and unpack image "registry.k8s.io/pause:3.10": failed to resolve reference "registry.k8s.io/pause:3.10": unexpected status from HEAD request to https://registry.k8s.io/v2/pause/manifests/3.10: 403 Forbidden
``` 
Does anyone know a place where I could start debugging?

Cilium version:
```
cilium-cli: v0.16.22-7-g6aa596fe2 compiled with go1.23.0 on linux/amd64
cilium image (default): v1.16.4
cilium image (stable): v1.16.5
cilium image (running): unknown. Unable to obtain cilium version. Reason: release: not found
```
I can curl to: `https://registry.k8s.io/v2/pause/manifests/3.10` from my local box and I get a 307 re-direct to: `https://us-east4-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.10` Maybe a bad/blocked Hetzzner IP?

UPDATE: Ok, twilight zone. I built it at a different Hetzner data center and it works.....

**Comment by mrclrchtr** [comment]
Hi, Short response with mobile phone: 
This is a known issue. Please see Readme section. Bad IP is correct. 

Closing this one. Feel free to reopen on further issues.
