### ISSUE TITLE
ARM or AMD

### ISSUE THREAD

**Issue by knfoo** [hcloud-talos/terraform-hcloud-talos#29]
Hi :wave: 

When reading the doc it states that packer creates X86 and AMD images, but reading the code it seems that it should be X86 and ARM.

https://github.com/hcloud-talos/terraform-hcloud-talos/blob/df1abd1432e3fe2f2974b4af98098d2ae5bc51ef/README.md?plain=1#L101

https://github.com/hcloud-talos/terraform-hcloud-talos/blob/df1abd1432e3fe2f2974b4af98098d2ae5bc51ef/_packer/talos-hcloud.pkr.hcl#L32

I would like to use ARM servers, just want to make sure that it is actually a possibility.

**Comment by mrclrchtr** [comment]
Yes, that is a mistake. It's about ARM. 

btw. AMD is also x86 ;)
