### ISSUE TITLE
Error: Error making request ipv6.icanhazip.com

### ISSUE THREAD

**Issue by segator** [hcloud-talos/terraform-hcloud-talos#31]
First of all pretty cool module I wanted to test it but running this TF module on WSL2 windows seems there is no IPV6, even if I do `enable_ipv6 = false` 
```
╷
│ Error: Error making request
│
│   with module.talos.data.http.personal_ipv6[0],
│   on .terraform/modules/talos/firewall.tf line 7, in data "http" "personal_ipv6":
│    7: data "http" "personal_ipv6" {
│
│ Error making request: GET https://ipv6.icanhazip.com giving up after 1 attempt(s): Get "https://ipv6.icanhazip.com": dial tcp [2606:4700::6810:b8f1]:443: connect: network is
│ unreachable
╵
```

**Comment by TeeTeufel** [comment]
This option `enable_ipv6 = false` only manages if a primary IPv6 should be assigned to the hcloud instances.

`firewall_use_current_ip   = true` tries to get your current public IPv4 and IPv6 your client will use to connect to the cluster.
If you have no public IPv6 address or it is not properly set up, this will fail.
The above mentioned option does not change this behavior.

You can use the options mentioned in this issue to set your current public IPv4 manually
https://github.com/hcloud-talos/terraform-hcloud-talos/issues/10#issuecomment-2119303813

**Comment by segator** [comment]
Oh good thanks!
