### ISSUE TITLE
Awesome project!

### ISSUE THREAD

**Issue by apricote** [hcloud-talos/terraform-hcloud-talos#35]
Just wanted to swing by and congratulate on the project! It works very well in my testing :)

I added it to our [awesome-hcloud](https://github.com/hetznercloud/awesome-hcloud) list: https://github.com/hetznercloud/awesome-hcloud/commit/9618cbb4d0452d1d96bce692823965dcbdc514ac

**Comment by mrclrchtr** [comment]
Thank you very much! It's always nice to get positive feedback.

**Comment by kuznero** [comment]
Thank you! This saves a lot of hours for a lot of people!
