### ISSUE TITLE
Add docs for 403 forbidden on gcr.io pull

### ISSUE THREAD

**Issue by mrclrchtr** [hcloud-talos/terraform-hcloud-talos#46]
![image](https://github.com/user-attachments/assets/e00ac93f-64b2-4cea-b3cc-b4aac20b1be0)

It's because of blacklisted IP.

https://github.com/kubernetes/registry.k8s.io/issues/138

**Comment by DennisJensen95** [comment]
Any workaround for this? I tried installing spegel, but i did not manage to make it work 😊

**Comment by mrclrchtr** [comment]
Hi, 

Unfortunately no... a Docker proxy would help. Spegel is unfortunately “too late” in the chain for it to help. I have been in contact with support. Here is the communication:

Hetzner
>  Unfortunately, some of our IPs are incorrectly located in Iran by some GeoIP databases. We cannot influence these databases. If this causes problems, please create a snapshot and create a new server with this snapshot. You can then delete the “faulty” server.

Me
> I work with Terraform and therefore probably get the same IP again and again. Even when completely deleting and recreating.

Hetzner
> Unfortunately, the IP assignment is random and cannot be influenced by us. However, if the current server is deleted after a new server has been created, it should be assigned a different IP address.

**Comment by conrity** [comment]
Install Harbor and use it as proxy for docker image registries. Talos supports Harbor. Worked for me.

**Comment by mrclrchtr** [comment]
You mean install Harbour somewhere else?

**Comment by conrity** [comment]
> You mean install Harbour somewhere else?

Yes, separate server in hetzner cloud, with "good" ip address. Use harbor robot token in talos registries configuration.
