### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by solarisfire** [hcloud-talos/terraform-hcloud-talos#89]
I'm getting the following deprecation warning when using this tool.

<pre>
│ Warning: Deprecated
│ 
│   with module.talos.data.talos_cluster_kubeconfig.this,
│   on .terraform/modules/talos/talos.tf line 130, in data "talos_cluster_kubeconfig" "this":
│  130: data "talos_cluster_kubeconfig" "this" {
│ 
│ Use `talos_cluster_kubeconfig` resource instead. This data source will be removed in the next minor version of the provider.
</pre>

**Comment by mrclrchtr** [comment]
Yes, I have to reactor the code a little bit. I also want to use the new health check of version 0.6.0.

Maybe next week I will find some time.

**Comment by mrclrchtr** [comment]
Unfortunately I could not get the health check to work. Probably because of https://github.com/siderolabs/terraform-provider-talos/issues/206 
it is at least the same error message: `service is not healthy: etcd`
