### ISSUE TITLE
Talos OS config should never use a floating IP.

### ISSUE THREAD

**Issue by solarisfire** [hcloud-talos/terraform-hcloud-talos#94]
I've been running into some issues, and I've been having some discussion with a Talos OS developer, and it would appear the issue is caused by the way the terraform-hcloud-talos module creates the talosconfig file.

If a floating IP is defined, the floating IP is placed into module.talos.talosconfig.

However, a floating IP should never be used for this (https://github.com/siderolabs/talos/issues/9441#issuecomment-2396849291)

It should instead be a list of control-plane IP addresses.

Documented here: https://www.talos.dev/v1.8/introduction/prodnotes/#endpoints

**Comment by mrclrchtr** [comment]
Oh, thank you very much for the info. I wasn't aware of that. I thought it would be useful to automatically use an available endpoint in this way. I will change that.
